parameters:
  sonarExecuteScan:
    token: "squ_f03ec7e40d29290af955ca530c527a9d04189c53"

steps:
  gradleExecuteBuild:
    path: app
    buildFlags:
        - clean
        - build
  sonarExecuteScan:
    serverUrl: http://haproxy:9000
    verbose: true
    projectKey: java-camera-viewer
    sonarScannerDownloadUrl: "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-7.0.2.4839-windows-x64.zip"
    token: "squ_f03ec7e40d29290af955ca530c527a9d04189c53"
