/*
 * This source file was generated by the Gradle 'init' task
 */
package ua.myhome.camera.viewer;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

public class App {
    public static void main(String[] args) throws IOException {
        PlayList resources = new PlayList();
        new CameraViewBoard(resources);
    }
}
